import type { Student, Students } from "@/types/student"

const mockStudentsData: Students = {
  "1": {
    id: "1",
    name: "Jiang Ian Wenkai",
    dateOfBirth: "April XX, 20XX",
    studentId: "28467382",
    vrAddress: "531 Lasuen Mall #19492, Stanford, CA 94305",
    graduationDate: "June 2029",
    grade: 10,
    gpa: 4.0,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 240,
    freshmanGPA: 4.0,
    sophomoreGPA: 4.0,
    juniorGPA: "N/A",
    seniorGPA: "N/A",
    courses: [
      {
        id: "1",
        name: "AP English Language and Composition",
        code: "ENG301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "HON",
        year: 9,
      },
      {
        id: "2",
        name: "AP Computer Science Principles",
        code: "CSC301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "CNJ3S5",
        subjectArea: "Computer Science",
        level: "HGHHNR",
        year: 9,
      },
      {
        id: "3",
        name: "AP European History",
        code: "HIS301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "PM956E",
        subjectArea: "History",
        level: "HON",
        year: 9,
      },
      {
        id: "4",
        name: "AP Statistics",
        code: "MAT301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "QS7A5X",
        subjectArea: "Mathematics",
        level: "HON",
        year: 9,
      },
      {
        id: "5",
        name: "INTSV Advanced Environmental Sci",
        code: "ENV301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "N6LNRQ",
        subjectArea: "Science",
        level: "HON",
        year: 9,
      },
      {
        id: "6",
        name: "ENRICHD Advanced Projects in Digital Arts",
        code: "ART301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual Perf Art",
        level: "HGHHNR",
        year: 9,
      },
      {
        id: "7",
        name: "INTSV BUILD INNOVATION & ENTREPRENEURSHIP",
        code: "BUS301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "QAL2W8",
        subjectArea: "College Prep",
        level: "CPREP",
        year: 9,
      },
      {
        id: "8",
        name: "ENRICHD Data Science Mathematics (Stanford)",
        code: "MAT302",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "LLKNS5",
        subjectArea: "Mathematics",
        level: "HON/DUAL",
        year: 9,
      },
      {
        id: "9",
        name: "AP Pre Calculus",
        code: "MAT303",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "MBRMQ6",
        subjectArea: "Mathematics",
        level: "HON",
        year: 9,
      },
      {
        id: "10",
        name: "INTSV 3D COMPUTER AIDED DESIGN",
        code: "CSC302",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "DW47FQ",
        subjectArea: "Computer Science",
        level: "ADV",
        year: 9,
      },
      {
        id: "11",
        name: "AP Chinese Language",
        code: "LAN301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "HON",
        year: 9,
      },
      {
        id: "12",
        name: "ACC Design Thinking",
        code: "DES301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "K62Q5G",
        subjectArea: "Design",
        level: "GFTED",
        year: 9,
      },
      {
        id: "13",
        name: "AP Chemistry",
        code: "CHE301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "TDRJH7",
        subjectArea: "Science",
        level: "HON",
        year: 9,
      },
      {
        id: "14",
        name: "AP Physics 1: Algebra Based",
        code: "PHY301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "EFWC4A",
        subjectArea: "Science",
        level: "HON",
        year: 9,
      },
      {
        id: "15",
        name: "INTSV Biology Honors",
        code: "BIO301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science",
        level: "HGHHON",
        year: 9,
      },
      {
        id: "16",
        name: "AP Microeconomics",
        code: "ECO301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "EKMF7G",
        subjectArea: "Social Science",
        level: "HON",
        year: 9,
      },
      {
        id: "17",
        name: "AP English Literature and Composition",
        code: "ENG401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "HON",
        year: 10,
      },
      {
        id: "18",
        name: "AP Biology",
        code: "BIO401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "R9B7NM",
        subjectArea: "Science",
        level: "HON",
        year: 10,
      },
      {
        id: "19",
        name: "AP World History: Modern",
        code: "HIS401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "TJ8AHE",
        subjectArea: "History",
        level: "HON",
        year: 10,
      },
      {
        id: "20",
        name: "AP United States History",
        code: "HIS402",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "HJ9C2B",
        subjectArea: "History",
        level: "HON",
        year: 10,
      },
      {
        id: "21",
        name: "AP Macroeconomics",
        code: "ECO401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "EKMF7G",
        subjectArea: "Social Science",
        level: "HON",
        year: 10,
      },
      {
        id: "22",
        name: "AP Environmental Science",
        code: "ENV401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "P5QAJ3",
        subjectArea: "Science",
        level: "HGHHNR",
        year: 10,
      },
      {
        id: "23",
        name: "GFTED Research in Tibet",
        code: "RES401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "ZNR2J4",
        subjectArea: "College Prep",
        level: "HON",
        year: 10,
      },
      {
        id: "24",
        name: "AP Calculus BC",
        code: "MAT401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "J8KLTN",
        subjectArea: "Mathematics",
        level: "HON",
        year: 10,
      },
      {
        id: "25",
        name: "AP Psychology",
        code: "PSY401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "MBXM7H",
        subjectArea: "Social Science",
        level: "HON",
        year: 10,
      },
      {
        id: "26",
        name: "ACC Design as Discovery (Stanford)",
        code: "DES401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "TX93D7",
        subjectArea: "Computer Science",
        level: "ADV",
        year: 10,
      },
      {
        id: "27",
        name: "AP Computer Science A",
        code: "CSC401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "JN43W9",
        subjectArea: "Computer Science",
        level: "HON",
        year: 10,
      },
      {
        id: "28",
        name: "ACC College Writing",
        code: "ENG402",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "J9TR5X",
        subjectArea: "English",
        level: "GFTED",
        year: 10,
      },
      {
        id: "29",
        name: "AP Physics 2: Algebra Based",
        code: "PHY401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "D2DTCB",
        subjectArea: "Science",
        level: "HON",
        year: 10,
      },
      {
        id: "30",
        name: "AP Physics C Mechanics",
        code: "PHY402",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "ALX47Y",
        subjectArea: "Science",
        level: "HON",
        year: 10,
      },
      {
        id: "31",
        name: "ADV Experimental Archaeology in VR",
        code: "ARC401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "KFA8SX",
        subjectArea: "Science",
        level: "HGHHON",
        year: 10,
      },
      {
        id: "32",
        name: "ENRICHD Government and Policy",
        code: "GOV401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "H3QAHT",
        subjectArea: "Social Science",
        level: "HON",
        year: 10,
      },
    ],
  },
  "2": {
    id: "2",
    name: "Emily Johnson",
    dateOfBirth: "May 15, 20XX",
    studentId: "28467383",
    vrAddress: "532 Lasuen Mall #19493, Stanford, CA 94305",
    graduationDate: "June 2030",
    grade: 9,
    gpa: 3.85,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 60,
    freshmanGPA: 3.85,
    sophomoreGPA: "N/A",
    juniorGPA: "N/A",
    seniorGPA: "N/A",
    courses: [
      {
        id: "1",
        name: "English 1",
        code: "ENG101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "2",
        name: "Algebra 1",
        code: "MATH101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "SHCZK6",
        subjectArea: "Mathematics",
        level: "Standard",
        year: 9,
      },
      {
        id: "3",
        name: "Biology",
        code: "BIO101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "4",
        name: "World History",
        code: "HIST101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PM956E",
        subjectArea: "History",
        level: "Standard",
        year: 9,
      },
      {
        id: "5",
        name: "Spanish 1",
        code: "SPAN101",
        credits: 5,
        grade: "B",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "Standard",
        year: 9,
      },
      {
        id: "6",
        name: "Physical Education",
        code: "PE101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Physical Education",
        level: "Standard",
        year: 9,
      },
      {
        id: "7",
        name: "Art 1",
        code: "ART101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Standard",
        year: 9,
      },
      {
        id: "8",
        name: "Health",
        code: "HLTH101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "XWFRGC",
        subjectArea: "Health",
        level: "Standard",
        year: 9,
      },
      {
        id: "9",
        name: "Computer Science Principles",
        code: "CSC101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "CNJ3S5",
        subjectArea: "Computer Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "10",
        name: "Environmental Science",
        code: "ENV101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "N6LNRQ",
        subjectArea: "Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "11",
        name: "Creative Writing",
        code: "ENG102",
        credits: 5,
        grade: "A",
        ucAgCourseId: "WKYR57",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "12",
        name: "Music Appreciation",
        code: "MUS101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Standard",
        year: 9,
      },
    ],
  },
  "3": {
    id: "3",
    name: "Michael Chen",
    dateOfBirth: "June 22, 20XX",
    studentId: "28467384",
    vrAddress: "533 Lasuen Mall #19494, Stanford, CA 94305",
    graduationDate: "June 2030",
    grade: 9,
    gpa: 4.0,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 60,
    freshmanGPA: 4.0,
    sophomoreGPA: "N/A",
    juniorGPA: "N/A",
    seniorGPA: "N/A",
    courses: [
      {
        id: "1",
        name: "Honors English 1",
        code: "ENG101H",
        credits: 5,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "Honors",
        year: 9,
      },
      {
        id: "2",
        name: "Geometry",
        code: "MATH201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "WKYR57",
        subjectArea: "Mathematics",
        level: "Advanced",
        year: 9,
      },
      {
        id: "3",
        name: "Honors Biology",
        code: "BIO101H",
        credits: 5,
        grade: "A",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science",
        level: "Honors",
        year: 9,
      },
      {
        id: "4",
        name: "AP World History",
        code: "HIST101AP",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PM956E",
        subjectArea: "History",
        level: "AP",
        year: 9,
      },
      {
        id: "5",
        name: "Mandarin 3",
        code: "MAND301",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "Advanced",
        year: 9,
      },
      {
        id: "6",
        name: "AP Computer Science Principles",
        code: "CSC101AP",
        credits: 5,
        grade: "A",
        ucAgCourseId: "CNJ3S5",
        subjectArea: "Computer Science",
        level: "AP",
        year: 9,
      },
      {
        id: "7",
        name: "Advanced Art",
        code: "ART201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Advanced",
        year: 9,
      },
      {
        id: "8",
        name: "Health",
        code: "HLTH101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "XWFRGC",
        subjectArea: "Health",
        level: "Standard",
        year: 9,
      },
      {
        id: "9",
        name: "AP Environmental Science",
        code: "ENV101AP",
        credits: 5,
        grade: "A",
        ucAgCourseId: "N6LNRQ",
        subjectArea: "Science",
        level: "AP",
        year: 9,
      },
      {
        id: "10",
        name: "Honors Chemistry",
        code: "CHEM101H",
        credits: 5,
        grade: "A",
        ucAgCourseId: "LLKNS5",
        subjectArea: "Science",
        level: "Honors",
        year: 9,
      },
      {
        id: "11",
        name: "Creative Writing",
        code: "ENG102",
        credits: 5,
        grade: "A",
        ucAgCourseId: "WKYR57",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "12",
        name: "Music Theory",
        code: "MUS201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Advanced",
        year: 9,
      },
    ],
  },
  "4": {
    id: "4",
    name: "Sophia Rodriguez",
    dateOfBirth: "July 3, 20XX",
    studentId: "28467385",
    vrAddress: "534 Lasuen Mall #19495, Stanford, CA 94305",
    graduationDate: "June 2030",
    grade: 9,
    gpa: 3.92,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 60,
    freshmanGPA: 3.92,
    sophomoreGPA: "N/A",
    juniorGPA: "N/A",
    seniorGPA: "N/A",
    courses: [
      {
        id: "1",
        name: "English 1",
        code: "ENG101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "2",
        name: "Algebra 1",
        code: "MATH101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "SHCZK6",
        subjectArea: "Mathematics",
        level: "Standard",
        year: 9,
      },
      {
        id: "3",
        name: "Biology",
        code: "BIO101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "4",
        name: "World History",
        code: "HIST101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "PM956E",
        subjectArea: "History",
        level: "Standard",
        year: 9,
      },
      {
        id: "5",
        name: "Spanish 2",
        code: "SPAN201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "Standard",
        year: 9,
      },
      {
        id: "6",
        name: "Art 1",
        code: "ART101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Standard",
        year: 9,
      },
      {
        id: "7",
        name: "Physical Education",
        code: "PE101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Physical Education",
        level: "Standard",
        year: 9,
      },
      {
        id: "8",
        name: "Health",
        code: "HLTH101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "XWFRGC",
        subjectArea: "Health",
        level: "Standard",
        year: 9,
      },
      {
        id: "9",
        name: "Computer Science Principles",
        code: "CSC101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "CNJ3S5",
        subjectArea: "Computer Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "10",
        name: "Environmental Science",
        code: "ENV101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "N6LNRQ",
        subjectArea: "Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "11",
        name: "Creative Writing",
        code: "ENG102",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "WKYR57",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "12",
        name: "Drama",
        code: "DRAM101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Standard",
        year: 9,
      },
    ],
  },
  "5": {
    id: "5",
    name: "Alexander Kim",
    dateOfBirth: "August 18, 20XX",
    studentId: "28467386",
    vrAddress: "535 Lasuen Mall #19496, Stanford, CA 94305",
    graduationDate: "June 2030",
    grade: 9,
    gpa: 3.75,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 60,
    freshmanGPA: 3.75,
    sophomoreGPA: "N/A",
    juniorGPA: "N/A",
    seniorGPA: "N/A",
    courses: [
      {
        id: "1",
        name: "English 1",
        code: "ENG101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "2",
        name: "Algebra 1",
        code: "MATH101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "SHCZK6",
        subjectArea: "Mathematics",
        level: "Standard",
        year: 9,
      },
      {
        id: "3",
        name: "Biology",
        code: "BIO101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "4",
        name: "World History",
        code: "HIST101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "PM956E",
        subjectArea: "History",
        level: "Standard",
        year: 9,
      },
      {
        id: "5",
        name: "Korean 1",
        code: "KOR101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "Standard",
        year: 9,
      },
      {
        id: "6",
        name: "Music Theory",
        code: "MUS101",
        credits: 5,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Standard",
        year: 9,
      },
      {
        id: "7",
        name: "Physical Education",
        code: "PE101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Physical Education",
        level: "Standard",
        year: 9,
      },
      {
        id: "8",
        name: "Health",
        code: "HLTH101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "XWFRGC",
        subjectArea: "Health",
        level: "Standard",
        year: 9,
      },
      {
        id: "9",
        name: "Computer Science Principles",
        code: "CSC101",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "CNJ3S5",
        subjectArea: "Computer Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "10",
        name: "Environmental Science",
        code: "ENV101",
        credits: 5,
        grade: "B+",
        ucAgCourseId: "N6LNRQ",
        subjectArea: "Science",
        level: "Standard",
        year: 9,
      },
      {
        id: "11",
        name: "Creative Writing",
        code: "ENG102",
        credits: 5,
        grade: "A-",
        ucAgCourseId: "WKYR57",
        subjectArea: "English",
        level: "Standard",
        year: 9,
      },
      {
        id: "12",
        name: "Orchestra",
        code: "MUS102",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "Standard",
        year: 9,
      },
    ],
  },
  "6": {
    id: "6",
    name: "Ellian D. Villalobos-Torres",
    dateOfBirth: "02/17/2007",
    studentId: "01364709VR",
    vrAddress: "19 South Delaware Street, San Mateo, CA 94401",
    graduationDate: "06/10/2025",
    grade: 12,
    gpa: 3.986,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 295,
    freshmanGPA: 3.875,
    sophomoreGPA: 3.714,
    juniorGPA: 4.125,
    seniorGPA: 4.188,
    courses: [
      {
        id: "1",
        name: "Algebra 1 F P",
        code: "MATH101",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "SHCZK6",
        subjectArea: "Mathematics (C)",
        level: "Standard",
        year: 9,
      },
      {
        id: "2",
        name: "Biology/Living Earth F",
        code: "BIO101",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science (D)",
        level: "Standard",
        year: 9,
      },
      {
        id: "3",
        name: "English 1 AS F P",
        code: "ENG101",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "YMES6W",
        subjectArea: "English (B)",
        level: "Standard",
        year: 9,
      },
      {
        id: "4",
        name: "Health F",
        code: "HLTH101",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "XWFRGC",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 9,
      },
      {
        id: "5",
        name: "PE 1 F",
        code: "PE101",
        credits: 5.0,
        grade: "B",
        level: "Standard",
        year: 9,
      },
      {
        id: "5",
        name: "PE 1 F",
        code: "PE101",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Non A-G",
        level: "Standard",
        year: 9,
      },
      {
        id: "6",
        name: "Spanish 3 F P",
        code: "SPAN301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Language Other than English (E)",
        level: "Standard",
        year: 9,
      },
      {
        id: "7",
        name: "AVID 1 F P",
        code: "AVID101",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "KXLACP",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 9,
      },
      {
        id: "8",
        name: "Algebra 1 S P",
        code: "MATH102",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "SHCZK6",
        subjectArea: "Mathematics (C)",
        level: "Standard",
        year: 9,
      },
      {
        id: "9",
        name: "Biology/Living Earth S",
        code: "BIO102",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science (D)",
        level: "Standard",
        year: 9,
      },
      {
        id: "10",
        name: "English 1 S P",
        code: "ENG102",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English (B)",
        level: "Standard",
        year: 9,
      },
      {
        id: "11",
        name: "PE 1 S",
        code: "PE102",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Non A-G",
        level: "Standard",
        year: 9,
      },
      {
        id: "12",
        name: "Spanish Native Speaker 3 S P",
        code: "SPAN302",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Language Other than English (E)",
        level: "Standard",
        year: 9,
      },
      {
        id: "13",
        name: "AVID 1 S P",
        code: "AVID102",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "KXLACP",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 9,
      },
      {
        id: "14",
        name: "Ethnic Studies",
        code: "ETHN101",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "DB6TGZ",
        subjectArea: "History/Social Science (A)",
        level: "Standard",
        year: 9,
      },
      {
        id: "15",
        name: "Chemistry Honors",
        code: "CHEM201",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "LLKNS5",
        subjectArea: "Science (D) Honors",
        level: "Honors",
        year: 10,
      },
      {
        id: "16",
        name: "English 2 F P",
        code: "ENG201",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "G3CART",
        subjectArea: "English (B)",
        level: "Standard",
        year: 10,
      },
      {
        id: "17",
        name: "Integrated Math 1 F P",
        code: "MATH201",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Mathematics (C)",
        level: "Standard",
        year: 10,
      },
      {
        id: "18",
        name: "Media Arts F P",
        code: "ART201",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "PTF4DP",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 10,
      },
      {
        id: "19",
        name: "Modern World History F P",
        code: "HIST201",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "TJ8AHE",
        subjectArea: "History/Social Science (A)",
        level: "Standard",
        year: 10,
      },
      {
        id: "20",
        name: "Government and Policy",
        code: "GOV201",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "DD6TGZ",
        subjectArea: "History/Social Science (A)",
        level: "Standard",
        year: 10,
      },
      {
        id: "21",
        name: "Experimental and Design",
        code: "DESIGN201",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "K62Q5G",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 10,
      },
      {
        id: "22",
        name: "Chemistry Honors",
        code: "CHEM202",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "LLKNS5",
        subjectArea: "Science (D) Honors",
        level: "Honors",
        year: 10,
      },
      {
        id: "23",
        name: "English 2 S P",
        code: "ENG202",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "G3CART",
        subjectArea: "English (B)",
        level: "Standard",
        year: 10,
      },
      {
        id: "24",
        name: "Integrated Math 1 S P",
        code: "MATH202",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "G3CART",
        subjectArea: "Mathematics (C)",
        level: "Standard",
        year: 10,
      },
      {
        id: "25",
        name: "Media Arts S P",
        code: "ART202",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "PTF4DP",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 10,
      },
      {
        id: "26",
        name: "Modern World History S P",
        code: "HIST202",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "TJ8AHE",
        subjectArea: "History/Social Science (A)",
        level: "Standard",
        year: 10,
      },
      {
        id: "27",
        name: "Service Learning Leadership",
        code: "LEAD201",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "N2KZC4",
        subjectArea: "Non A-G",
        level: "Standard",
        year: 10,
      },
      {
        id: "28",
        name: "Creative Writing",
        code: "ENG301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "WKYR57",
        subjectArea: "English (B)",
        level: "Standard",
        year: 10,
      },
      {
        id: "29",
        name: "AP Spanish Language HP",
        code: "SPAN401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "GQ2GMA",
        subjectArea: "Language Other than English (E) AP",
        level: "AP",
        year: 11,
      },
      {
        id: "30",
        name: "English 3 F P",
        code: "ENG301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "RH2CJ5",
        subjectArea: "English (B)",
        level: "Standard",
        year: 11,
      },
      {
        id: "31",
        name: "Geometry F P",
        code: "MATH301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "WKYR57",
        subjectArea: "Mathematics (C)",
        level: "Standard",
        year: 11,
      },
      {
        id: "32",
        name: "Physics F P",
        code: "PHYS301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "K53PGC",
        subjectArea: "Science (D) Honors",
        level: "Honors",
        year: 11,
      },
      {
        id: "33",
        name: "Study Skills/SEL",
        code: "STUDY301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "N2KZC4",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 11,
      },
      {
        id: "34",
        name: "US History F P",
        code: "HIST301",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "HJ9C2B",
        subjectArea: "History/Social Science (A)",
        level: "Standard",
        year: 11,
      },
      {
        id: "35",
        name: "Visual Art F P",
        code: "ART301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts (F)",
        level: "Standard",
        year: 11,
      },
      {
        id: "36",
        name: "Work Experience Education Program",
        code: "WORK301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 11,
      },
      {
        id: "37",
        name: "AP Spanish Language HP",
        code: "SPAN402",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "GQ2GMA",
        subjectArea: "Language Other than English (E) AP",
        level: "AP",
        year: 11,
      },
      {
        id: "38",
        name: "English 3 S P",
        code: "ENG302",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "RH2CJ5",
        subjectArea: "English (B)",
        level: "Standard",
        year: 11,
      },
      {
        id: "39",
        name: "Geometry S P",
        code: "MATH302",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "WKYR57",
        subjectArea: "Mathematics (C)",
        level: "Standard",
        year: 11,
      },
      {
        id: "40",
        name: "Physics S P",
        code: "PHYS302",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "K53PGC",
        subjectArea: "Science (D)",
        level: "Standard",
        year: 11,
      },
      {
        id: "41",
        name: "Economics",
        code: "ECON301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "EKMF7G",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 11,
      },
      {
        id: "42",
        name: "US History S P",
        code: "HIST302",
        credits: 5.0,
        grade: "B",
        ucAgCourseId: "HJ9C2B",
        subjectArea: "History/Social Science (A)",
        level: "Standard",
        year: 11,
      },
      {
        id: "43",
        name: "Visual Art S P",
        code: "ART302",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts (F)",
        level: "Standard",
        year: 11,
      },
      {
        id: "44",
        name: "Advanced Environmental Science",
        code: "ENV301",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "N6LNRQ",
        subjectArea: "Science (D)",
        level: "Advanced",
        year: 11,
      },
      {
        id: "45",
        name: "Government Honors",
        code: "GOV401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "H3QAHT",
        subjectArea: "History/Social Science (A) Honors",
        level: "Honors",
        year: 12,
      },
      {
        id: "46",
        name: "English 12 Honors",
        code: "ENG401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English (B) Honors",
        level: "Honors",
        year: 12,
      },
      {
        id: "47",
        name: "Business Management",
        code: "BUS401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "QAL2W8",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 12,
      },
      {
        id: "48",
        name: "Kinesiology",
        code: "KIN401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Standard",
        year: 12,
      },
      {
        id: "49",
        name: "A.I Senior Capstone",
        code: "AI401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "DW47FQ",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Advanced",
        year: 12,
      },
      {
        id: "50",
        name: "Marine Biology (Oceanography)",
        code: "BIO401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "GQR75J",
        subjectArea: "Science (D)",
        level: "Standard",
        year: 12,
      },
      {
        id: "51",
        name: "Advanced Photojournalism",
        code: "JOUR401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "J9TR5X",
        subjectArea: "College-Preparatory Elective (G)",
        level: "Advanced",
        year: 12,
      },
      {
        id: "52",
        name: "Statistics Honors",
        code: "MATH401",
        credits: 5.0,
        grade: "A",
        ucAgCourseId: "QS7A5X",
        subjectArea: "Mathematics (C) Honors",
        level: "Honors",
        year: 12,
      },
    ],
  },
  "7": {
    id: "7",
    name: "Agathe Bertin",
    dateOfBirth: "February 7, 2007",
    studentId: "28467382",
    vrAddress: "818 Northampton Dr, Palo Alto, CA 94303",
    graduationDate: "June 2025",
    grade: 12,
    gpa: 4.0,
    enrollmentStatus: "Good Standing",
    cumulativeCredits: 460,
    freshmanGPA: 4.0,
    sophomoreGPA: 4.0,
    juniorGPA: 4.0,
    seniorGPA: 4.0,
    courses: [
      // Grade 9 (2021-2022)
      {
        id: "1",
        name: "AP Computer Science A",
        code: "CSC101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "JN43W9",
        subjectArea: "Computer Science",
        level: "HON",
        year: 9,
      },
      {
        id: "2",
        name: "Conceptual Physics",
        code: "PHY101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "K53PGC",
        subjectArea: "Science",
        level: "CPREP",
        year: 9,
      },
      {
        id: "3",
        name: "English 9",
        code: "ENG101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "CPREP",
        year: 9,
      },
      {
        id: "4",
        name: "Geometry",
        code: "MATH101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "WKYR57",
        subjectArea: "Mathematics",
        level: "HON",
        year: 9,
      },
      {
        id: "5",
        name: "World History: Cultures and Historical Geography",
        code: "HIST101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "TJ8AHE",
        subjectArea: "History",
        level: "CPREP",
        year: 9,
      },
      {
        id: "6",
        name: "Introduction to Psychology: Human Behavior",
        code: "PSY101",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "MBXM7H",
        subjectArea: "Social Science",
        level: "ADV",
        year: 9,
      },
      {
        id: "7",
        name: "Biology",
        code: "BIO101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "HK3WME",
        subjectArea: "Science",
        level: "HON",
        year: 9,
      },
      {
        id: "8",
        name: "Journalism",
        code: "JOUR101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "J9TR5X",
        subjectArea: "English",
        level: "CPREP",
        year: 9,
      },
      {
        id: "9",
        name: "Design Thinking",
        code: "DES101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "K62Q5G",
        subjectArea: "Design",
        level: "CPREP",
        year: 9,
      },
      {
        id: "10",
        name: "Physical Education",
        code: "PE101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "TFXCPZ",
        subjectArea: "Physical Education",
        level: "REG",
        year: 9,
      },
      {
        id: "11",
        name: "French 1",
        code: "FREN101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "CPREP",
        year: 9,
      },
      {
        id: "12",
        name: "Russian 1",
        code: "RUSS101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "REG",
        year: 9,
      },
      {
        id: "13",
        name: "Visual Art",
        code: "ART101",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "CPREP",
        year: 9,
      },

      // Grade 10 (2022-2023)
      {
        id: "14",
        name: "Design Lab: Moonshots Thinking",
        code: "DES201",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "K62Q5G",
        subjectArea: "Design",
        level: "HON",
        year: 10,
      },
      {
        id: "15",
        name: "Data Science Mathematics",
        code: "MATH201",
        credits: 10,
        grade: "A",
        ucAgCourseId: "LLKNS5",
        subjectArea: "Mathematics",
        level: "HON",
        year: 10,
      },
      {
        id: "16",
        name: "Russian 2",
        code: "RUSS201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "REG",
        year: 10,
      },
      {
        id: "17",
        name: "Algebra 2",
        code: "MATH202",
        credits: 10,
        grade: "A",
        ucAgCourseId: "SHCZK6",
        subjectArea: "Mathematics",
        level: "ACC",
        year: 10,
      },
      {
        id: "18",
        name: "French 2",
        code: "FREN201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "REG",
        year: 10,
      },
      {
        id: "19",
        name: "AP European History",
        code: "HIST201",
        credits: 10,
        grade: "A",
        ucAgCourseId: "PM956E",
        subjectArea: "History",
        level: "AP",
        year: 10,
      },
      {
        id: "20",
        name: "AP Physics 1",
        code: "PHY201",
        credits: 10,
        grade: "A",
        ucAgCourseId: "EFWC4A",
        subjectArea: "Science",
        level: "HON",
        year: 10,
      },
      {
        id: "21",
        name: "Advanced Authentic Research",
        code: "RES201",
        credits: 5,
        grade: "A",
        ucAgCourseId: "ZNR2J4",
        subjectArea: "College Prep",
        level: "ADV",
        year: 10,
      },
      {
        id: "22",
        name: "Astronomy",
        code: "ASTR201",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "QS7A5X",
        subjectArea: "Science",
        level: "REG",
        year: 10,
      },
      {
        id: "23",
        name: "Chemistry",
        code: "CHEM201",
        credits: 10,
        grade: "A",
        ucAgCourseId: "TDRJH7",
        subjectArea: "Science",
        level: "HON",
        year: 10,
      },
      {
        id: "24",
        name: "English 10 Honors",
        code: "ENG201",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "G3CART",
        subjectArea: "English",
        level: "HON",
        year: 10,
      },
      {
        id: "25",
        name: "Computer Science: Object-Oriented Programming",
        code: "CSC201",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "JN43W9",
        subjectArea: "Computer Science",
        level: "HON",
        year: 10,
      },
      {
        id: "26",
        name: "Visual Art",
        code: "ART201",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "PTF4DP",
        subjectArea: "Visual & Performing Arts",
        level: "REG",
        year: 10,
      },

      // Grade 11 (2023-2024)
      {
        id: "27",
        name: "Moonshots (Internship)",
        code: "INTERN301",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "ZNR2J4",
        subjectArea: "College Prep",
        level: "ADV",
        year: 11,
      },
      {
        id: "28",
        name: "French 3",
        code: "FREN301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "ADV",
        year: 11,
      },
      {
        id: "29",
        name: "Design Thinking (Moonshots)",
        code: "DES301",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "K62Q5G",
        subjectArea: "Design",
        level: "ADV",
        year: 11,
      },
      {
        id: "30",
        name: "AP English Literature",
        code: "ENG301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "HON",
        year: 11,
      },
      {
        id: "31",
        name: "Russian 3",
        code: "RUSS301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "REG",
        year: 11,
      },
      {
        id: "32",
        name: "Precalculus",
        code: "MATH301",
        credits: 10,
        grade: "A",
        ucAgCourseId: "MBRMQ6",
        subjectArea: "Mathematics",
        level: "HON",
        year: 11,
      },
      {
        id: "33",
        name: "Biology",
        code: "BIO301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "R9B7NM",
        subjectArea: "Science",
        level: "HON",
        year: 11,
      },
      {
        id: "34",
        name: "Statistical Thinking",
        code: "STAT301",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QS7A5X",
        subjectArea: "Mathematics",
        level: "HON",
        year: 11,
      },
      {
        id: "35",
        name: "Community Service",
        code: "SERV301",
        credits: 5,
        grade: "A",
        ucAgCourseId: "N2KZC4",
        subjectArea: "College-Preparatory Elective",
        level: "CPREP",
        year: 11,
      },
      {
        id: "36",
        name: "Spanish 4 (Cypress College Prep)",
        code: "SPAN401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "CPREP",
        year: 11,
      },
      {
        id: "37",
        name: "AP Language",
        code: "ENG302",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "AP",
        year: 11,
      },
      {
        id: "38",
        name: "Civics",
        code: "CIV301",
        credits: 5,
        grade: "A",
        ucAgCourseId: "H3QAHT",
        subjectArea: "Social Science",
        level: "CPREP",
        year: 11,
      },
      {
        id: "39",
        name: "US History",
        code: "HIST301",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "HJ9C2B",
        subjectArea: "History",
        level: "CPREP",
        year: 11,
      },

      // Grade 12 (2024-2025)
      {
        id: "40",
        name: "AP English Literature",
        code: "ENG401",
        credits: 10,
        grade: "A",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "AP",
        year: 12,
      },
      {
        id: "41",
        name: "French 4",
        code: "FREN401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "CPREP",
        year: 12,
      },
      {
        id: "42",
        name: "Advanced Science Research",
        code: "SCI401",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "ZNR2J4",
        subjectArea: "Science",
        level: "ADV",
        year: 12,
      },
      {
        id: "43",
        name: "Product Design and Managing Roles (Moonshots)",
        code: "DES401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "K62Q5G",
        subjectArea: "Design",
        level: "ACC",
        year: 12,
      },
      {
        id: "44",
        name: "Internet Inf. on Devices & World Coverage",
        code: "TECH401",
        credits: 5,
        grade: "A",
        ucAgCourseId: "DW47FQ",
        subjectArea: "Computer Science",
        level: "HON",
        year: 12,
      },
      {
        id: "45",
        name: "Astrobiology",
        code: "BIO402",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "GQR75J",
        subjectArea: "Science",
        level: "HON",
        year: 12,
      },
      {
        id: "46",
        name: "Russian 4",
        code: "RUSS401",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "QYDT67",
        subjectArea: "Foreign Language",
        level: "CPREP",
        year: 12,
      },
      {
        id: "47",
        name: "Artificial Intelligence: Large Language Models",
        code: "AI401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "JN43W9",
        subjectArea: "Computer Science",
        level: "ADV",
        year: 12,
      },
      {
        id: "48",
        name: "Senior Capstone Project",
        code: "CAP401",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "ZNR2J4",
        subjectArea: "College Prep",
        level: "CPREP",
        year: 12,
      },
      {
        id: "49",
        name: "Advanced Data Science Mathematics",
        code: "MATH401",
        credits: 5,
        grade: "A+",
        ucAgCourseId: "LLKNS5",
        subjectArea: "Mathematics",
        level: "ADV",
        year: 12,
      },
      {
        id: "50",
        name: "Computer Science 101 (Stanford Online)",
        code: "CSC402",
        credits: 10,
        grade: "A",
        ucAgCourseId: "JN43W9",
        subjectArea: "Computer Science",
        level: "ENRCHD",
        year: 12,
      },
      {
        id: "51",
        name: "English 12 Honors",
        code: "ENG402",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "YMES6W",
        subjectArea: "English",
        level: "HON",
        year: 12,
      },
      {
        id: "52",
        name: "Economics",
        code: "ECON401",
        credits: 10,
        grade: "A+",
        ucAgCourseId: "EKMF7G",
        subjectArea: "Social Science",
        level: "CPREP",
        year: 12,
      },
    ],
  },
}

export async function getStudentData(id: string): Promise<Student | null> {
  if (!id) {
    console.error("No student ID provided")
    return null
  }
  const student = mockStudentsData[id]
  if (!student) {
    console.error(`Student with id ${id} not found`)
    return null
  }
  return student
}

export async function getAllStudents(): Promise<Students> {
  return mockStudentsData
}

